# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44197d46b1c69b45d0165e210e19af37b43eb3f917d6b6d285439700e553d7e400a60a7eea60a20ea59448649a8dfc366fc54957c6beff278446d1f0a65e0daa

test:
  secret_key_base: 5e7a8fc860cdcf03539eba8910877b9963a397815d6e64641fa93186c52c820a85cf5aef474447894f907a94078fd6e2c05a8b0e4b9699b27d264d91eafdf4c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
